name: whiteboard_sdk_flutter
description: A Flutter wrapper for netless whiteboard
version: 0.2.1
homepage: https://github.com/netless-io/Whiteboard-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.2"

dependencies:
  flutter_inappwebview: ^5.3.2
  webview_flutter: ^3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/whiteboardBridge/